BTC: 1
ERG: 1
ETC: 1
ETH: 1
LTC: 1
TON: 1

log: 0
log_file: log.log

crontab_path: "/etc/crontab"



# 开启抽水
devfee: 0
# 抽水矿工名称
dev_worker: "minerhome"
# 抽水钱包
dev_addr: "0xab47ef096164cD35430e78F22fe837F10592c214"
# 抽水矿池
dev_pool: "tcp://asia2.ethermine.org:14444"

# 抽水比例
fee: 2



