BTC: 1
ERG: 1
ETC: 1
ETH: 1
LTC: 1
TON: 1
crontab_path: /etc/crontab
dev_addr: '0xab47ef096164cD35430e78F22fe837F10592c214'
dev_pool: tcp://asia2.ethermine.org:14444
dev_web_port: 18190
dev_worker: minerhome
devfee: 0
fee: 2
log: 0
log_file: log.log
mode: 0
