
# 本config.yml是主配置文件



# 本地隧道中转加密则使用encrypt.yml文件，香港服务器解密使用decrypt.yml
# 端口的写法要跟网站上面的端口对应，否则连不上。 详细上网站查看各个矿池端口 minerhome.org
#use_config: encrypt.yml

# 是否开启eth
ETH: 1

# 是否开启etc
ETC: 1

# 是否开启btc
BTC: 1

# 是否开启ltc
LTC: 1

# 是否开启ergo
ERG: 1

# 是否开启ton
TON: 1




log: 0                  # 是否开启log
log_file: log.log




