
# 本config.yml是主配置文件


# 本地隧道中转加密则使用encrypt.yml文件，香港服务器解密使用decrypt.yml
# 端口的写法要跟网站上面的端口对应，否则连不上。 详细上网站查看各个矿池端口 minerhome.org
use_config: encrypt.yml
#use_config: decrypt.yml


log: 0                  # 是否开启log
log_file: log.log



# 加密到哪个中转, 把延迟低的放到前面，具体地址可以找群主要 比如说把 bj.eth666.org 换成 bj.eth555.org
tunnel_to:
  - sz.minertunnel.org





# 使用流量混淆，本地机可以开启，香港落地机没必要
use_mess: 1

